Add support to Portuguese - Brazil language (pt-BR)
nohello-net/site pull request #35
Opened 2022-03-04 04:35 UTC by celsofabri

### Description
- Created new path `/br/` (Portuguese - Brazil);
- Added translations to pt-BR locale;
- Added new Brazilian greetings on the dynamic title.
![giphy](https://user-images.githubusercontent.com/6715718/156699901-02d9a4e2-30c9-4d1e-b832-91665e0c649c.gif)

2022-03-04 04:45 UTC, celsofabri commented
I loved your site and I would wanna contribute to it. So, I added the Portuguese (Brazil) version! I hope that you like it @notjosh :)

2022-03-04 12:48 UTC, angeliski commented on locales/br/messages.po
> +"As pessoas que fazem isso geralmente tentam ser educadas, não indo direto ao ponto, como geralmente fariam pessoalmente ou por telefone - e isso é ótimo! Mas é !@#$ e chat não precisa disso. Para a
Something is wrong here, the year should be in a different format
```suggestion
"As pessoas que fazem isso geralmente tentam ser educadas, não indo direto ao ponto, como geralmente fariam pessoalmente ou por telefone - e isso é ótimo! Mas é %1$s e chat não precisa disso. Para a maioria das pessoas, digitar é muito mais lento do que falar. Então, apesar das melhores intenções, **você está apenas fazendo a outra pessoa esperar** para você formular sua pergunta, o que é perda de produtividade (e às vezes um pouco irritante).\n"
```

2022-03-04 13:27 UTC, celsofabri commented on locales/br/messages.po
> +"As pessoas que fazem isso geralmente tentam ser educadas, não indo direto ao ponto, como geralmente fariam pessoalmente ou por telefone - e isso é ótimo! Mas é !@#$ e chat não precisa disso. Para a
Thanks, @angeliski ! For some reason, it changed and I didn't see it.

2022-03-09 14:23 UTC, vitormattos requested changes

2022-03-09 14:23 UTC, vitormattos commented on locales/br/messages.po
> +msgstr "14h20m"
```suggestion
msgstr "14:20"
```

2022-03-09 14:23 UTC, vitormattos commented on locales/br/messages.po
> +msgstr "14h15m"
```suggestion
msgstr "14:15"
```

2022-03-09 14:23 UTC, vitormattos commented on locales/br/messages.po
> +msgstr "Isso é meio sério (meio 👀) então por favor não fique [bravo](https://www.youtube.com/watch?v=xzpndHtdl9A) com a pessoa que te enviou aqui."
```suggestion
msgstr "Isso é meio sério (meio 👀) então por favor não fique [bravo](https://www.youtube.com/watch?v=xzpndHtdl9A) com a pessoa que te enviou este site."
```

2022-03-09 14:23 UTC, vitormattos commented on locales/br/messages.po
> +"Language: en\n"
```suggestion
"Language: br\n"
```

2022-03-09 21:14 UTC, notjosh commented
https://nohello.net/pt-br/ 🥳

2022-03-09 21:14 UTC, closed without merging