Added language: Dutch
nohello-net/site pull request #69
Opened 2022-04-04 18:52 UTC by jesse01987

2022-04-12 13:31 UTC, timwienk requested changes
Ik ben even de vertalingen doorgegaan. Ik kwam daarbij een aantal (spellings)foutjes tegen, en een paar suggesties om te verbeteren.

Hopelijk helpt het!

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +"Zie je hoe Keith eigenlijk minuten eerder zijn antwoord had kunnen hebben, zonder Tim te laten wachten. Sterker nog, Tim had eigenlijk al direct kunnen nadenken over zijn antwoord!\n"
De eerste zin is geschreven als een vraag (wat me goed lijkt), waardoor achter `wachten` zou een `?` moeten staan, in plaats van een `.`.

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +"Mensen die dit doen willen doorgaans gewoon beleeft zijn, zoals je elkaar in persoon of aan de telefoon zou groeten - en dat is natuurlijk prima! Maar het is %1$s en chats zijn iets totaal anders. V
Een paar suggesties:
- `beleefd` is met een `d`
- eventueel `begroeten` i.p.v. `groeten` (hoewel beide werken)
- `**moet de ander nu op je wachten**` i.p.v. `**je laat de ander alleen maar langer wachten**`
- `doordat je de vraag nog niet hebt gesteld` i.p.v. `door je vraag uit te stellen`

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +msgstr "✅ Probeer eens dit"
Misschien beter: `Probeer dit eens`

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +"Als je denkt dat het onbeleefd is om in een chat direct na \"hoi\" je vraagt te stellen... **Er zijn genoeg andere manieren om het tóch vriendelijk te houden.**\n"
De zin (en bedoeling) loopt iets beter met `andere` weg, denk ik

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +"- \"Heyhey! Hopelijk gaat alles goed. Vraagje, kun je mij even bellen zodra je tijd hebt? :)\"\n"
Dit lijkt me niet zo'n goede oplossing :sweat_smile:

Beter ook erbij waar het over gaat dan: `kunnen we even over de planning bellen zodra je tijd hebt? :)`

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +"- \"Hi! Wanneer je het niet al te druk hebt, kun je mij die ene mail nog naar me doorsturen?\"\n"
Woordje `mij` kan weg

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +msgstr "Deze pagina is grappig bedoeld (een beetje 👀) dus geen reden om [boos](https://www.youtube.com/watch?v=xzpndHtdl9A) te worden op diegene die je deze link heeft gestuurd."
Misschien beter: `👀) dus` vervangen door `👀) en is dus`

2022-04-12 13:31 UTC, timwienk commented on locales/nl/messages.po
> +msgstr "Website gebasseerd op [nohello.com](https://web.archive.org/web/20131127020115/http://www.nohello.com/). De afbeeldingen zijn afkomstig van *[The Office](https://en.wikipedia.org/wiki/The_Off
`gebaseerd` is met één `s`

2022-04-12 13:52 UTC, timwienk commented on locales/nl/messages.po
> +"- \"Heyhey! Hopelijk gaat alles goed. Vraagje, kun je mij even bellen zodra je tijd hebt? :)\"\n"
Bij de regel erboven mag `trouwens` ook met een hoofdletter, trouwens. :grin:

2022-04-12 13:53 UTC, timwienk commented on locales/nl/messages.po
> +"- \"Hey sophie - korte vraag.\"\n"
In het Engels staat hier ook `sophie`, maar eigenlijk zou hier natuurlijk `Sophie` met een hoofdletter moeten staan.

(Bonuspunten als je er `Soof` van maakt.)

2022-04-19 09:35 UTC, jesse01987 commented on locales/nl/messages.po
> +"Zie je hoe Keith eigenlijk minuten eerder zijn antwoord had kunnen hebben, zonder Tim te laten wachten. Sterker nog, Tim had eigenlijk al direct kunnen nadenken over zijn antwoord!\n"
```suggestion
"Zie je hoe Keith eigenlijk minuten eerder zijn antwoord had kunnen hebben, zonder Tim te laten wachten? Sterker nog, Tim had eigenlijk al direct kunnen nadenken over zijn antwoord!\n"
```

2022-04-19 09:35 UTC, jesse01987 commented on locales/nl/messages.po
> +"Mensen die dit doen willen doorgaans gewoon beleeft zijn, zoals je elkaar in persoon of aan de telefoon zou groeten - en dat is natuurlijk prima! Maar het is %1$s en chats zijn iets totaal anders. V
```suggestion
"Mensen die dit doen willen doorgaans gewoon beleefd zijn, zoals je elkaar in persoon of aan de telefoon zou groeten - en dat is natuurlijk prima! Maar het is %1$s en chats zijn iets totaal anders. Voor de meeste mensen is typen is veel trager dan spreken. Dus ondanks je beste bedoelingen, **je laat de ander alleen maar langer wachten** door je vraag uit te stellen, wat niet echt effectief is (en best irritant).\n"
```

2022-04-19 09:36 UTC, jesse01987 commented on locales/nl/messages.po
> +"- \"Hey sophie - korte vraag.\"\n"
```suggestion
"- \"Hey Soof - korte vraag.\"\n"
```

2022-04-19 09:37 UTC, jesse01987 commented on locales/nl/messages.po
> +msgstr "Website gebasseerd op [nohello.com](https://web.archive.org/web/20131127020115/http://www.nohello.com/). De afbeeldingen zijn afkomstig van *[The Office](https://en.wikipedia.org/wiki/The_Off
```suggestion
msgstr "Website gebaseerd op [nohello.com](https://web.archive.org/web/20131127020115/http://www.nohello.com/). De afbeeldingen zijn afkomstig van *[The Office](https://en.wikipedia.org/wiki/The_Office_(British_TV_series))*. Open-source op [GitHub](https://github.com/nohello-net/site)."
```

2022-04-19 09:37 UTC, jesse01987 commented on locales/nl/messages.po
> +msgstr "Deze pagina is grappig bedoeld (een beetje 👀) dus geen reden om [boos](https://www.youtube.com/watch?v=xzpndHtdl9A) te worden op diegene die je deze link heeft gestuurd."
```suggestion
msgstr "Deze pagina is grappig bedoeld (een beetje 👀) en is dus geen reden om [boos](https://www.youtube.com/watch?v=xzpndHtdl9A) te worden op diegene die je deze link heeft gestuurd."
```

2022-04-19 09:38 UTC, jesse01987 commented on locales/nl/messages.po
> +"Mensen die dit doen willen doorgaans gewoon beleeft zijn, zoals je elkaar in persoon of aan de telefoon zou groeten - en dat is natuurlijk prima! Maar het is %1$s en chats zijn iets totaal anders. V
```suggestion
"Mensen die dit doen willen doorgaans gewoon beleeft zijn, zoals je elkaar in persoon of aan de telefoon zou begroeten - en dat is natuurlijk prima! Maar het is %1$s en chats zijn iets totaal anders. Voor de meeste mensen is typen is veel trager dan spreken. Dus ondanks je beste bedoelingen, **je laat de ander alleen maar langer wachten** door je vraag uit te stellen, wat niet echt effectief is (en best irritant).\n"
```

2022-04-19 09:39 UTC, jesse01987 commented on locales/nl/messages.po
> +"Mensen die dit doen willen doorgaans gewoon beleeft zijn, zoals je elkaar in persoon of aan de telefoon zou groeten - en dat is natuurlijk prima! Maar het is %1$s en chats zijn iets totaal anders. V
```suggestion
"Mensen die dit doen willen doorgaans gewoon beleeft zijn, zoals je elkaar in persoon of aan de telefoon zou groeten - en dat is natuurlijk prima! Maar het is %1$s en chats zijn iets totaal anders. Voor de meeste mensen is typen is veel trager dan spreken. Dus ondanks je beste bedoelingen, **moet de ander nu op je wachten** door je vraag uit te stellen, wat niet echt effectief is (en best irritant).\n"
```

2022-04-19 10:00 UTC, jesse01987 commented
@timwienk
Bedankt voor alle suggesties! Alles is verwerkt 👍🏻😄

2022-04-19 10:41 UTC, timwienk commented on locales/nl/messages.po
> +"Als je denkt dat het onbeleefd is om in een chat direct na \"hoi\" je vraagt te stellen... **Er zijn genoeg manieren om het tóch vriendelijk te houden.**\n"
Oeps, hier valt me nu nog iets op wat ik eerder niet zag:

Er staat `je vraagt te stellen` (moet zijn: `je vraag te stellen`).

2022-04-19 10:43 UTC, timwienk commented
I believe that, after this last comment is resolved, this is good to be merged, @notjosh. :wink:

2022-04-19 12:46 UTC, jesse01987 commented on locales/nl/messages.po
> +"Als je denkt dat het onbeleefd is om in een chat direct na \"hoi\" je vraagt te stellen... **Er zijn genoeg manieren om het tóch vriendelijk te houden.**\n"
Nice, scherp! :) Done: https://github.com/nohello-net/site/pull/69/commits/4d4b9b3808ba3b23fc32ab30d536543d3d9e8634

2022-04-21 16:53 UTC, timwienk approved these changes

2022-06-27 13:04 UTC, closed without merging

2023-11-10 09:16 UTC, metbril commented
These never got merged?